//! Admin operation identity routing is shared by lifecycle verification.

use testlab_schema::{OperationId, ScenarioAction};

pub(crate) fn operation_id(action: &ScenarioAction) -> Option<&OperationId> {
    Some(match action {
        ScenarioAction::CreateTopic(value) => &value.operation_id,
        ScenarioAction::CreateTopicsBatch(value) => &value.operation_id,
        ScenarioAction::CreatePartitions(value) => &value.operation_id,
        ScenarioAction::DeleteTopic(value) => &value.operation_id,
        ScenarioAction::DeleteTopics(value) => &value.operation_id,
        ScenarioAction::DescribeTopic(value) => &value.operation_id,
        ScenarioAction::DescribeTopics(value) => &value.operation_id,
        ScenarioAction::ListTopics(value) => &value.operation_id,
        ScenarioAction::ListConfigResources(value) => &value.operation_id,
        ScenarioAction::ListOffsets(value) => &value.operation_id,
        ScenarioAction::ListOffsetsBatch(value) => &value.operation_id,
        ScenarioAction::DeleteRecords(value) => &value.operation_id,
        ScenarioAction::DeleteRecordsBatch(value) => &value.operation_id,
        ScenarioAction::DescribeTopicConfig(value) => &value.operation_id,
        ScenarioAction::DescribeTopicConfigs(value) => &value.operation_id,
        ScenarioAction::AlterTopicConfigs(value) => &value.operation_id,
        ScenarioAction::AlterTopicConfig(value) => &value.operation_id,
        ScenarioAction::DescribeCluster(value) => &value.operation_id,
        ScenarioAction::DescribeFeatures(value) => &value.operation_id,
        ScenarioAction::ValidateFeatureUpdates(value) => &value.operation_id,
        ScenarioAction::ExerciseDelegationTokenLifecycle(value) => &value.operation_id,
        ScenarioAction::ExerciseStreamsGroupAdminLifecycle(value) => &value.operation_id,
        ScenarioAction::DescribeProducers(value) => &value.operation_id,
        ScenarioAction::ListTransactions(value) => &value.operation_id,
        ScenarioAction::DescribeTransactions(value) => &value.operation_id,
        ScenarioAction::FenceProducers(value) => &value.operation_id,
        ScenarioAction::AlterPartitionReassignments(value) => &value.operation_id,
        ScenarioAction::ListPartitionReassignments(value) => &value.operation_id,
        ScenarioAction::ElectLeaders(value) => &value.operation_id,
        ScenarioAction::DescribeLogDirs(value) => &value.operation_id,
        ScenarioAction::DescribeReplicaLogDirs(value) => &value.operation_id,
        ScenarioAction::AlterReplicaLogDirs(value) => &value.operation_id,
        ScenarioAction::DescribeMetadataQuorum(value) => &value.operation_id,
        ScenarioAction::ListConsumerGroups(value) => &value.operation_id,
        ScenarioAction::DescribeConsumerGroup(value) => &value.operation_id,
        ScenarioAction::ListConsumerGroupOffsets(value) => &value.operation_id,
        ScenarioAction::AlterConsumerGroupOffset(value) => &value.operation_id,
        ScenarioAction::DeleteConsumerGroupOffset(value) => &value.operation_id,
        ScenarioAction::DeleteConsumerGroup(value) => &value.operation_id,
        ScenarioAction::DeleteConsumerGroups(value) => &value.operation_id,
        ScenarioAction::RemoveConsumerGroupMembers(value) => &value.operation_id,
        ScenarioAction::ListConsumerGroupOffsetsBatch(value) => &value.operation_id,
        ScenarioAction::ListConsumerGroupsOffsets(value) => &value.operation_id,
        ScenarioAction::AlterConsumerGroupOffsets(value) => &value.operation_id,
        ScenarioAction::DeleteConsumerGroupOffsets(value) => &value.operation_id,
        ScenarioAction::DescribeClassicGroups(value) => &value.operation_id,
        ScenarioAction::DescribeConsumerGroups(value) => &value.operation_id,
        ScenarioAction::CreateAcls(value) => &value.operation_id,
        ScenarioAction::DescribeAcls(value) => &value.operation_id,
        ScenarioAction::DeleteAcls(value) => &value.operation_id,
        ScenarioAction::AlterClientQuota(value) => &value.operation_id,
        ScenarioAction::DescribeClientQuota(value) => &value.operation_id,
        ScenarioAction::AlterUserScramCredential(value) => &value.operation_id,
        ScenarioAction::DescribeUserScramCredential(value) => &value.operation_id,
        ScenarioAction::DescribeShareGroup(value) => &value.operation_id,
        ScenarioAction::DescribeShareGroups(value) => &value.operation_id,
        ScenarioAction::ListShareGroupOffsets(value) => &value.operation_id,
        ScenarioAction::ListShareGroupsOffsets(value) => &value.operation_id,
        ScenarioAction::AlterShareGroupOffsets(value) => &value.operation_id,
        ScenarioAction::DeleteShareGroupOffsets(value) => &value.operation_id,
        ScenarioAction::DeleteShareGroups(value) => &value.operation_id,
        _ => return None,
    })
}
